export const FILES = {
  'welcome': {
    'content': [
      ['\x1b[34;1mSay Cheong\x1b[0m'],
      [''],
      ['\x1b[37;1m│\x1b[0m \x1b[37;2mA software engineer with a background in mathematics always looking for fun\x1b[0m'],
      ['\x1b[37;1m│\x1b[0m \x1b[37;2mproblems to solve.\x1b[0m'],
      ['\x1b[36m         ________          \x1b[0m'],
      ['\x1b[36m       /         /\\        \x1b[0m'],
      ['\x1b[36m      /         /  \\       \x1b[0mName: Seongyoon "Say" Cheong'],
      ['\x1b[36m     /         /    \\      \x1b[0mOccupation: Software Engineer'],
      ['\x1b[36m    /________ /      \\     \x1b[0mResidence: <ADDRESS_PATTERN>', { type: 'link', pattern: '<ADDRESS_PATTERN>', url: '<ADDRESS_URL>' }],
      ['\x1b[36m    \\         \\      /     \x1b[0mHomepage: <HOMEPAGE_PATTERN>', { type: 'link', pattern: '<HOMEPAGE_PATTERN>', url: '<HOMEPAGE_URL>' }],
      ['\x1b[36m     \\         \\    /      \x1b[0mGithub: <GITHUB_PATTERN>', { type: 'link', pattern: '<GITHUB_PATTERN>', url: '<GITHUB_URL>' }],
      ['\x1b[36m      \\         \\  /       \x1b[0mMail: <EMAIL_PATTERN>', { type: 'link', pattern: '<EMAIL_PATTERN>', url: '<EMAIL_URL>' }],
      ['\x1b[36m       \\ ________\\/        \x1b[0m'],
      ['\x1b[36m                           \x1b[0m'],
      ['Powered by xterm.js', { type: 'link', pattern: 'xterm.js', url: 'https://xtermjs.org'}],
      [''],
      ['Welcome to \x1b[38;5;208;1mUbuntu\x1b[0m 24.04.3 LTS (GNU/Linux 6.14.0)'], // Host machine environment
      ['For the best viewing experience, a keyboard and a mouse are recommended.'],
      ['Below is a simple emulated terminal, try running \'help\'.', { type: 'command', pattern: 'help', url: '' }],
    ],
    'permission': 'x',
  },
  'matrix': {
    'content': [['']],
    'permission': 'x',
  },
  'fluid': {
    'content': [['']],
    'permission': 'x',
  },
  'resume.md': {
    'content': [
      ['# Say Cheong'],
      [''],
      ['## Contact'],
      [''],
      ['- Email: <EMAIL_PATTERN>', { type: 'link', pattern: '<EMAIL_PATTERN>', url: '<EMAIL_URL>' }],
      ['- Mobile: <TEL_PATTERN>', { type: 'link', pattern: '<TEL_PATTERN>', url: '<TEL_URL>' }],
      ['- Residence: <ADDRESS_PATTERN>', { type: 'link', pattern: '<ADDRESS_PATTERN>', url: '<ADDRESS_URL>' }],
      ['- Homepage: <HOMEPAGE_PATTERN>', { type: 'link', pattern: '<HOMEPAGE_PATTERN>', url: '<HOMEPAGE_URL>' }],
      ['- Github: <GITHUB_PATTERN>', { type: 'link', pattern: '<GITHUB_PATTERN>', url: '<GITHUB_URL>' }],
      [''],
      ['## Summary'],
      [''],
      ['A software engineer with a foundation in mathematics. A lifelong programmer'],
      ['passionate about all things technology-related. Excels at distilling complex'],
      ['problems into their core logical components to create elegant and holistic'],
      ['solutions.'],
      [''],
      ['## Experience'],
      [''],
      ['### Blockchain Engineer'],
      [''],
      ['Planetarium Labs                                               2021.03 - 2024.12', { type: 'link', pattern: 'Planetarium Labs', url: 'https://planetariumlabs.com'}],
      [''],
      ['- Identified and optimized critical performance bottlenecks in search and'],
      ['  serialization algorithms, improving data throughput while reducing memory'],
      ['  footprint by orders of magnitude.'],
      ['- Finalized the implementation of algorithmically complex core components such'],
      ['  as the Merkle Patricia Trie and Bencodex, filling in missing features and'],
      ['  resolving logic flaws to allow data migration on a live network.'],
      ['- Served as the core repository\'s top contributor, reducing the total codebase'],
      ['  size through refactoring while simultaneously delivering major feature sets'],
      ['  and performance improvements.'],
      ['- Hardened the P2P networking layer for a distributed system, resolving critical'],
      ['  race conditions to ensure a more robust system.'],
      [''],
      ['### Algorithm Engineer'],
      [''],
      ['Spacewalk                                                      2019.06 - 2020.12', { type: 'link', pattern: 'Spacewalk', url: 'https://spacewalk.tech'}],
      [''],
      ['- Developed core computational components with extensive use of computational'],
      ['  geometry and linear programming.'],
      ['- Established on-premise infrastructure from the ground up. Standardized'],
      ['  development environments and implemented secure remote access protocols.'],
      [''],
      ['### Machine Learning Researcher'],
      [''],
      ['Clunix                                                         2018.02 - 2018.04', { type: 'link', pattern: 'Clunix', url: 'https://www.clunix.com' }],
      [''],
      ['- Conducted exploratory NLP research on Korean morphological analysis, assessing'],
      ['  the feasibility of experimental architectures such as Hierarchical Temporal'],
      ['  Memory and non-backpropagation networks.'],
      ['- Engineered data ingestion pipelines to scale the training corpus and'],
      ['  modernized the team\'s workflow by integrating Git/GitLab for version control.'],
      [''],
      ['## Skills'],
      [''],
      ['### Core Strengths'],
      [''],
      ['- Software Design, Advanced Algorithms & Data Structures, Code Optimization,'],
      ['  Collaborative Development with Git'],
      [''],
      ['### Programming Languages'],
      [''],
      ['- C#, Python, Java, C'],
      [''],
      ['### Tools & Environment'],
      [''],
      ['- Linux, Bash, Git, Vim, AWS/GCP, Docker, LaTeX'],
      [''],
      ['### Knowledge Domains'],
      [''],
      ['- Blockchain, Distributed Systems, Cryptography, Computational Geometry, Linear'],
      ['  Programming, Graph Theory, Data Science'],
      [''],
      ['### Spoken Languages'],
      [''],
      ['- Bilingual in English and Korean'],
      [''],
      ['## Education'],
      [''],
      ['### M.S. Mathematics'],
      [''],
      ['POSTECH                                                                  2015.08', { type: 'link', pattern: 'POSTECH', url: 'https://www.postech.ac.kr'}],
      [''],
      ['### B.S. Mathematics'],
      [''],
      ['SUNY Stony Brook                                                         2009.12', { type: 'link', pattern: 'SUNY Stony Brook', url: 'https://stonybrook.edu'}],
    ],
    'permission': 'r',
  },
  'about.md': {
    'content': [
      ['# Say Cheong'],
      [''],
      ['> I know that I know nothing.'],
      [''],
      ['> A cynic is what an idealist calls a realist.'],
      [''],
      ['## About'],
      [''],
      ['I am a software engineer with a background in mathematics, always looking for a'],
      ['challenging and fun problem to solve.'],
      [''],
      ['The details below, together with my resume and portfolio, should paint a good'],
      ['picture of my approach to engineering and the philosophy behind my work.'],
      [''],
      ['## Stack'],
      [''],
      ['Things I have picked up along the way.'],
      [''],
      ['Main Languages:'],
      [''],
      ['- BASIC: Learned at the age of eight. Where it all started.'],
      ['- C: Exposure to a "real" language. Taught me how computers actually work.'],
      ['- Java: From high school and college curriculum. Learned beyond "just coding".'],
      ['- Python / C#: For professional work. Developed production-level products.'],
      ['- English and Korean: Acquired natively. Bilingual.'],
      [''],
      ['Random Stuff:'],
      [''],
      ['- Linux: Out of curiosity. My daily driver.'],
      ['- Bash: From using Linux. Used to automate tasks.'],
      ['- LaTeX: For writing papers. Preferred over Word and PowerPoint.'],
      ['- Perl: As a side project over a weekend, just for fun. Why not.'],
      ['- HTML / CSS / JS: To occasionally create websites. Such as this page.'],
      ['- Libraries / Frameworks: Whenever deemed necessary. Too numerous to list.'],
      [''],
      ['## Interests'],
      [''],
      ['Subjects of interest within my fields of work.'],
      [''],
      ['Computer Science:'],
      [''],
      ['- Programming Language Theory'],
      ['- Theory of Computation'],
      ['- Algorithms & Data Structures'],
      [''],
      ['Mathematics:'],
      [''],
      ['- Abstract Algebra'],
      ['- Combinatorics'],
      ['- Logic & Set Theory'],
      [''],
      ['## Preferences'],
      [''],
      ['How I like to work, when given the choice.'],
      [''],
      ['- Linux > Windows / Mac OS'],
      ['- Editors > IDEs'],
      ['- Design > Coding'],
      ['- Performance > Features'],
      ['- Spaces > Tabs'],
      [''],
      ['## Hobbies'],
      [''],
      ['Other activities I enjoy doing.'],
      [''],
      ['- Video Games'],
      ['- Piano'],
      ['- Skating'],
    ],
    'permission': 'r',
  },
  'portfolio.md': {
    'content': [
      ['# Portfolio'],
      [''],
      ['A curated list of past works.'],
      [''],
      ['## Work'],
      [''],
      ['### Libplanet'],
      [''],
      ['[image] [link]', { type: 'image', pattern: 'image', url: '/images/nine_chronicles.png' }, { type: 'link', pattern: 'link', url: 'https://github.com/planetarium/libplanet' }],
      [''],
      ['- Blockchain engine for decentralized online multiplayer games.'],
      ['- Focused on the core blockchain structure, data serialization and encoding,'],
      ['  consensus protocol, and network protocol.'],
      ['- Keywords: C#, Open Source, Blockchain, Distributed Systems, Cryptography,'],
      ['  Network, Consensus, Database'],
      [''],
      ['### Large Scale Housing Layout Optimization'],
      [''],
      ['[image] [link]', { type: 'image', pattern: 'image', url: '/images/large_housing.gif' }, { type: 'link', pattern: 'link', url: 'https://spacewalk.tech' }],
      [''],
      ['- Site planning optimization for large apartment complex real estates.'],
      ['- Utilized computational geometry and topology to implement real-time'],
      ['  pathfinding to maximize space efficiency under legal and physical constraints.'],
      ['- Keywords: Python, Computational Geometry, Topology, Shapely'],
      [''],
      ['### Small Scale Housing Layout Optimization'],
      [''],
      ['[image] [link]', { type: 'image', pattern: 'image', url: '/images/small_housing.gif' }, { type: 'link', pattern: 'link', url: 'https://spacewalk.tech' }],
      [''],
      ['- Building layout optimization for small apartment building real estates.'],
      ['- Used mixed integer programming to optimize the layout regarding unit'],
      ['  placement and value.'],
      ['- Keywords: Python, Mixed Integer Programming, PuLP'],
      [''],
      ['## Personal'],
      [''],
      ['### Cubelink'],
      [''],
      ['[image] [link]', { type: 'image', pattern: 'image', url: '/images/cubelink.png' }, { type: 'link', pattern: 'link', url: 'https://github.com/greymistcube/cubelink.cloud' }],
      [''],
      ['- Website with terminal interface.'],
      ['- Built for hosting a personal homepage.'],
      [''],
      ['### Telescope'],
      [''],
      ['[image] [link]', { type: 'image', pattern: 'image', url: '/images/telescope.png' }, { type: 'link', pattern: 'link', url: 'https://github.com/planetarium/Telescope' }],
      [''],
      ['- Lightweight terminal GUI blockchain explorer.'],
      ['- Designed to assist state inspection and debugging at work.'],
      [''],
      ['### NEAT Experiments'],
      [''],
      ['[image_flappy] [link_flappy]', { type: 'image', pattern: 'image_flappy', url: '/images/flappy_bird_neat.gif'}, { type: 'link', pattern: 'link_flappy', url: 'https://github.com/greymistcube/flappy_bird_neat' }],
      ['[image_racing] [link_racing]', { type: 'image', pattern: 'image_racing', url: '/images/racing_game_neat.gif'}, { type: 'link', pattern: 'link_racing', url: 'https://github.com/greymistcube/racing_game_neat' }],
      [''],
      ['- Training AI using NEAT reinforcement learning algorithm to play simple games.'],
      ['- A proof of concept for learning neural networks and machine learning.'],
    ],
    'permission': 'r',
  }
};
